setwd("C:\\Users\\ece-lab\\Downloads")
install.packages(c("rpart", "rpart.plot", "caTools"))
library(rpart)
library(rpart.plot)
library(caTools)
data <- read.csv("classicification.csv",stringsAsFactors = TRUE)
head(data)
set.seed(123)
split<-sample.split(data$class,SplitRatio = 0.7)
train_data <- subset(data,split == TRUE)
test_data <- subset(data,split == FALSE)
model <- rpart(class ~.,data = train_data,method = "class")
rpart.plot(model)
predictions<-prdict(model,test_data$class,predictions)
print(confusion_matrix)
accuracy<-sum(diag(confusion_matrix)) /sum(confusion_matrix)
cat("Accuracy:", round(accuracy*100,2),"%n")
