install.packages(c("random forest","catools"))
library(random forest)
library(catools)
data<_read.csv("classification csv",stringasfacter=TRUE)
head(data)
set.seed(123)
split<_sample.split(dataclass,splitratio=0.7)
train_data<-subset(data,split=TRUE)
test_data<-random forest(class,data=train_data,ntree=100,importance=TRUE)
print(vf_model)
predection-predict(rf_model,test_data)
confusion_matrix<table(test.data$class,precdiction)
print(confusion_matrix)
accuracy<.sum(diag(confusion_matrix))/9sumconfusion_matrix)
cat("model accuracy:",round(accuracy 100,2),%n")
importance(rf.model)
varimpplot(rf.model)
